dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
      - g++-10

sudo: false

script:
  # This script could be run from any CI
  - export CC=gcc-10
  - export CXX=g++-10
  - bash travis.sh
  