DROP DATABASE GOT;
CREATE DATABASE GOT;
USE GOT;

CREATE TABLE IF NOT EXISTS REPOSITORIO
(
id INT NOT NULL PRIMARY  KEY  AUTO_INCREMENT,
nombre VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMMITS
(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
rep_id INT NOT NULL,
FOREIGN KEY (rep_id) REFERENCES REPOSITORIO(id),
autor VARCHAR(128) NOT NULL,
mensaje VARCHAR(255),
hora TIME
);

CREATE TABLE IF NOT EXISTS ARCHIVO(
ruta VARCHAR(512) NOT NULL PRIMARY KEY, 
commit_id INT NOT NULL,
FOREIGN KEY (commit_id) REFERENCES COMMITS(id),
huffman_code MEDIUMTEXT,
huffman_tree TEXT(655353)
);

-- Tabla de  cambios 
CREATE TABLE IF NOT EXISTS DIFF( 
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
commit_id INT NOT NULL,
FOREIGN KEY (commit_id) REFERENCES COMMITS(id),
archivo VARCHAR(512) NOT NULL, 
FOREIGN KEY (archivo) REFERENCES ARCHIVO(ruta),
diff_output TEXT(65535) NOT NULL
);
