DROP DATABASE GOT;
CREATE DATABASE GOT;
USE GOT;

CREATE TABLE IF NOT EXISTS REPOSITORIO
(
id INT NOT NULL PRIMARY  KEY,
nombre VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMMITS
(
ID INT NOT NULL PRIMARY KEY,
REPID INT NOT NULL,
FOREIGN KEY (REPID) REFERENCES REPOSITORY(ID),
AUTHOR VARCHAR(128) NOT NULL,
MESSAGE VARCHAR(255),
HOUR TIME
);

CREATE TABLE IF NOT EXISTS HUFFMANFILE(
Nombre NOT NULL PRIMARY KEY, 
Commit_Id INT NOT NULL,
FOREIGN KEY (CommitId) REFERENCES COMMITS(Id),
Huffman_Code MEDIUMTEXT,
Huffman_Tree TEXT(655353)
);

-- Tabla de  cambios 
CREATE TABLE IF NOT EXISTS DIFF( 
ID INT NOT  NULL PRIMARY KEY,
COMMITID INT NOT NULL,
FOREIGN KEY (COMMITID) REFERENCES COMMITS(ID),
FILEID INT NOT NULL, 
FOREIGN KEY (FILEID) REFERENCES HUFFMANFILE(ID),
DIFFOUTPUT TEXT(65535) NOT NULL
);