CREATE DATABASE GOT;
SELECT GOT;

CREATE TABLE REPOSITORY(
ID INT NOT NULL PRIMARY  KEY,
NAME VARCHAR NOT NULL
);

CREATE TABLE GOTIGNORE(
REPID INT NOT NULL,
FOREIGN KEY (REPID) REFERENCES REPOSITORY(ID),
FILESTRING VARCHAR NOT NULL);

CREATE TABLE COMMMITS(
ID INT NOT NULL PRIMARY KEY,
REPID INT NOT NULL,
FOREIGN KEY (REPID) REFERENCES REPOSITORY(ID),
AUTHOR VARCHAR NOTNULL,
MESSAGE VARCHAR,
HOUR TIME);


CREATE TABLE FILES(
ID INT NOT NULL PRIMARY KEY, 
COMMITID INT NOT NULL,
FOREIGN KEY (COMMITID) REFERENCES COMMITS(ID),
HUFFMANCODE MEDIUMTEXT,
HUFFMANTREE TEXT);


-- Tabla de  cambios 
CREATE TABLE DIFF( 
ID INT NOT  NULL PRIMARY KEY,
COMMITID INT NOT NULL,
FOREIGN KEY (COMMITID) REFERENCES COMMITS(ID),
FILEID INT NOT NULL, 
FOREIGN KEY (FILEID) REFERENCES FILES(ID),
DIFFOUTPUT VARCHAR NOT NULL);

