POST http://localhost:3000/init
content-type: application/json

{
    "name":"psssssop"
}

###

POST http://localhost:3000/api
content-type: application/json

{
    "type":"int",
    "password":"446b7563ea3f7519ee4d2b5753efb669"

}


###